export const STANDARD_KOCHGERAETE = [
  {
    name: "Schnellkochtopf",
    programme: ["Druck", "Dampf", "Kochen", "Anbraten"],
    leistungen: ["Niedrig", "Medium", "Hoch"],
    icon: "pressure",
    hintergrund: "#FFF3E0",
    rand: "#FF8C00",
  },
  {
    name: "Kochtopf",
    programme: ["Kochen", "Dämpfen", "Blanchieren"],
    leistungen: ["Niedrig", "Medium", "Hoch"],
    icon: "cooking-pot",
    hintergrund: "#E8F5E9",
    rand: "#2E7D32",
  },
  {
    name: "Mikrowelle",
    programme: ["Backen", "Auftauen", "Erwärmen", "Grillen", "Popcorn", "Dampf"],
    leistungen: ["Niedrig", "Medium", "Hoch", "800W", "900W", "1000W"],
    icon: "microwave",
    hintergrund: "#E3F2FD",
    rand: "#1565C0",
  },
  {
    name: "Backofen",
    programme: ["Backen", "Grillen", "Umluft", "Oberhitze", "Unterhitze"],
    leistungen: ["150°C", "180°C", "190°C", "200°C", "220°C"],
    icon: "flame",
    hintergrund: "#FCE4EC",
    rand: "#C62828",
  },
  {
    name: "Gasofen",
    programme: ["Backen", "Grillen", "Umluft", "Oberhitze", "Unterhitze", "Pizza"],
    leistungen: ["150°C", "180°C", "190°C", "200°C", "220°C", "250°C"],
    icon: "flame",
    hintergrund: "#FFF8E1",
    rand: "#F57F17",
  },
  {
    name: "Pfanne",
    programme: ["Braten", "Anbraten", "Schmoren"],
    leistungen: ["Niedrig", "Medium", "Hoch"],
    icon: "cooking-pot",
    hintergrund: "#F3E5F5",
    rand: "#6A1B9A",
  },
  {
    name: "Grill",
    programme: ["Grillen", "Direkt", "Indirekt", "Räuchern"],
    leistungen: ["Niedrig", "Medium", "Hoch"],
    icon: "flame",
    hintergrund: "#FBE9E7",
    rand: "#BF360C",
  },
];
